### ISSUE TITLE
Procedure fails to run with NULL Violation on major_id when distributed availability group exists

### ISSUE THREAD

**Issue by MrGoodbyte** [strdco/sp_help_permissions#1]
Hi, I attempted to run the help_permissions proc on a database server containing a Distributed Availability Group to another cluster for DR purposes. Unfortunately the replica_metadata_id is null in the returned data and this results in an attempt to insert a null value into the metadata_id column in @securables_temp.
![image](https://user-images.githubusercontent.com/32943438/81140706-b8288980-8fad-11ea-8755-5cf84395360c.png)

To get past it for now I added WHERE ag.is_distributed = 0 to the query as my current requirement does not include AG permissions specifically

**Comment by dhmacher** [comment]
I've updated the script to exclude AG replicas where the replica_metadata_id is null. When I have the time to set up a working lab AG, I'll try to create a more permanent fix.

Thanks for your feedback!
