### ISSUE TITLE
change from:'CERTIFICATE' to:'ASYMMETRIC KEY'

### ISSUE THREAD

**Issue by RickyLively** [strdco/sp_help_permissions#4]
from:
    -- ASYMMETRIC_KEY
    SELECT 0 AS parent_class, 0 AS parent_major_id, 26 AS class, asymmetric_key_id AS major_id, principal_id, 'CERTIFICATE', N'CERTIFICATE::'+QUOTENAME([name]), 0 AS is_server_lvl
    FROM sys.asymmetric_keys)

to:
    -- ASYMMETRIC_KEY
    SELECT 0 AS parent_class, 0 AS parent_major_id, 26 AS class, asymmetric_key_id AS major_id, principal_id, 'ASYMMETRIC KEY', N'ASYMMETRIC KEY::'+QUOTENAME([name]), 0 AS is_server_lvl
    FROM sys.asymmetric_keys)

**Comment by dhmacher** [comment]
Forgot to close this issue. Thanks, Ricky!
